# Generated by Django 5.0.7 on 2024-07-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinaryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binary_code', models.CharField(max_length=200)),
                ('translated_text', models.TextField()),
            ],
        ),
    ]
